name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - run: python create-fods.py samples/data-types.json data-types.fods
    - run: python create-fods.py samples/accounts.json accounts.fods
