name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: debian:trixie
    steps:
    - uses: actions/checkout@v4 
    - name: Install LibreOffice
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends libreoffice-calc-nogui python3

    - run: python create-fods.py samples/data-types.json data-types.fods
    - run: python create-fods.py samples/accounts.json accounts.fods

    - name: Convert to csv via LibreOffice to test if it can read the files (data-types)
      run: |
        libreoffice --headless --convert-to csv:"Text - txt - csv (StarCalc)":"44,34,76,1,,1031,true,true" data-types.fods --outdir .

    - name: Convert to csv via LibreOffice to test if it can read the files (accounts)
      run: |
        libreoffice --headless --convert-to csv:"Text - txt - csv (StarCalc)":"44,34,76,1,,1031,true,true" accounts.fods --outdir .

    - run: cat data-types.csv
    - run: cat accounts.csv
